apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service 
spec:
  type: NodePort 
  selector:
    name: result-app-pod
  ports:
      - port: 80
        targetPort: 80
        NodePort: 30002